spring.application.name=WellRx

spring.datasource.url=jdbc:mysql://${MYSQL_HOST:wellrx-db.cz8k8a84a9f2.us-east-2.rds.amazonaws.com}:3306/well_rx?createDatabaseIfNotExist=true
spring.datasource.username=${MYSQL_USERNAME:admin}
spring.datasource.password=${MYSQL_PASSWORD:Fofinho222}

spring.jpa.hibernate.ddl-auto=none

app.base-url=${APP_BASE_URL:http://localhost:8080}

spring.mail.host=smtp.gmail.com
spring.mail.port=${EMAIL_PORT}
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.expiration=${JWT_EXPIRATION}
jwt.refreshExpiration=${JWT_REFRESH_EXPIRATION}
jwt.key=${JWT_SECRET_KEY}